packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - icu-minify@4.14.1
  - next-intl-swc-plugin-extractor@4.14.1
  - next-intl@4.14.1
  - use-intl@4.14.1
